### ISSUE TITLE
Video freezing going back 

### ISSUE THREAD

**Issue by ballanz89** [webslides/WebSlides#33] opened 2017-02-01 09:01 UTC
I have two consequential video slides. When I go back from the second one, the video in the first slide freeze.

**Comment by jlantunez** [comment] 2017-02-01 09:37
Hi Ballanz,

Thanks. I'll check it out.

**Comment by Belelros** [comment] 2017-02-23 12:34
Hey @ballanz89 could you provide more information?

I'd appreciate if you could share the two slides you see problems with and your browser information to be able to reproduce your issue and try to fix it.

**Comment by Belelros** [comment] 2017-03-12 21:05
Going to close this @ballanz89 . If you could add more information we might be able to reproduce this.

Thanks!

**Comment by ballanz89** [comment] 2017-03-13 07:59
Hi @Belelros!

https://webslides.tv/demos/landings#slide=76

The video starts.

Arrow right (slide 77), then arrow left (back to the slide 76): video stopped.

Chrome 56.0.2924.87

**Comment by Belelros** [comment] 2017-03-19 21:45
This seems to be fixed as of a8734a57d333280adc139cc94433030bc349d8ff . Will keep it open though till this is merged.

**Closed** 2017-04-20 10:23 UTC
Labels: bug, status: dev complete
